#!/usr/bin/env bash
msg=$(head -n1 "$1")
if ! echo "$msg" | grep -qE '^(feat|fix|docs|chore|build|ci|refactor|test|polish)(\(.+\))?: .+'; then
  echo "ERROR: commit subject must match Conventional Commits format."
  exit 1
fi
