#!/usr/bin/env bash
while read local_ref local_sha remote_ref remote_sha; do
  if [[ "$remote_ref" == "refs/heads/main" ]]; then
    echo "ERROR: direct push to main is forbidden. Open a PR."
    exit 1
  fi
done
